const express=require("express")
const router=express.Router()
const userSignUpController=require("../controller/user/userSignup")
const userSignInController=require("../controller/user/userSignin")
const userDetailController=require("../controller/user/useDetails")
const alluserController=require("../controller/user/allUsers")
const getProductController=require("../controller/product/getProduct")
const updateProductController=require("../controller/product/updateProduct")
const getCategoryProductOne=require("../controller/product/getCategoryProductOne")
const getCategoryWiseProduct=require("../controller/product/getCategoryWiseProduct")
const getProductDetails=require("../controller/product/getProductDetails")
const addToCartController=require("../controller/user/addToCart")
const userLogout=require("../controller/user/userLogout")
const authToken=require('../middleware/authToken')
const updateUser=require('../controller/user/updateUser')
const upoadProductController=require('../controller/product/uploadProduct')
const { checkCartController, checkCartCountController } = require("../controller/product/checkCart");
router.post("/signup",userSignUpController)
router.post("/signin",userSignInController)
router.get("/user-details",authToken,userDetailController)
router.get("/userLogout",userLogout)
router.get("/all-users",authToken,alluserController)
router.post("/update-user",authToken,updateUser)
router.post("/upload-product",authToken,upoadProductController)
router.get("/get-products",getProductController)
router.post("/update-product",authToken,updateProductController)
router.get("/get-category-product",getCategoryProductOne)
router.get("/category-wise-roduct",getCategoryWiseProduct)
router.post("/product-details",getProductDetails)
router.post("/addtocart",authToken,addToCartController)
router.get('/checkCart/:productId',authToken, checkCartController);
router.get('/checkCartcount',authToken, checkCartCountController);
module.exports=router

//First page router